#!/usr/bin/python
#coding=utf-8
import zlib
exec zlib.decompress('xÚmSMoÛ0½÷W=Q‰ìÕµ—5œÃŠa—†ÚƒaJÌ¨dI´ý÷#4[‹Ù(Q|üxÏ>D?fQ¹Œƒiqu`_xÓÓÿ|…¶÷$ôr”Zi\nï¶CT/­UãnP¶÷U\r±-åžÖ¶5	#P=P®ª»ZácvÚJm1&|½=ÐöÞ[+ÞýÆ}2dýNÙ	DqƒJ(_uýR<Í¾®×’–ïÅ©¨†ÐòlÆ%àëòVHüì!DÛõ¶ßQ¥h<”y)é‡¯	¶bQç+Y‹¾ûì¡)¸.¨Ó¢Àâr-÷´bN6_‹f„@G¤È…ì"ÔLXÖPS\0ÙœÒ÷Â²˜¡0{ï±bÎf$õè#õd‹à7@Ó\¶â@a*3.;n‘E~·ÙP-"!s°°]sÛsº™¯Ó(âj–rôÇ	YPÝþs}2Þ%Î©¯-éJºÈ%x0ŸÌž¸6œ0‘ûcœ|ShrMoSÂñãÍõ>úizV&^“*c;¸ªo¾±N+	?Ö«´¨õØ‘æ&1šêdþ”NCn*ÅÎs—Ø(÷ü!©á—y%.aAÎ˜û%„Üvy™c/`;â½ÏÙ3_èœWts‰]Ó`^.	7rÁ±«ûî¦g®Ã_®ÁKÅ¹å.÷c`¶ùÐ0åô€ÚMœ~®ÆÅ6gGuªÆA<KèÿÁK9ºbý&ÖJ…PÄ£ñâ<*u')